model:
  name: 'bfe'
  pretrained: True
  # load_weights: 'log/occludedduke(60.4%)/model.pth.tar-90'
  # resume: 'log/Cm55p3/model.pth.tar-70'

data:
  type: 'image'
  # sources: ['market1501']
  # targets: ['partialreid']
  sources: ['occludedduke']   #occludedduke
  targets: ['occludedduke']   #pdukereid DUKEMTMC-REID  dukemtmcreid
  height: 384
  width: 128
  combineall: False
  transforms: ['random_flip'] # 'color_jitter' ## train on Market1501 test on O/P datasets
  save_dir: 'log/partialE'
  workers: 16
#  norm_mean: [0.4300, 0.4236, 0.4393]  # mean and std of occludedduke
#  norm_std: [0.1954, 0.1987, 0.1863]

sampler:
  train_sampler: 'RandomSampler'


loss:
  name: 'softmax'
  softmax:
    label_smooth: True


train:
  optim: adam
  lr: 0.0003
  max_epoch: 90
  batch_size: 64
  fixbase_epoch: 5
  open_layers: ['res_part1', 'res_part2', 'classifier1', 'classifier2', 'reduction1', 'reduction2', 'batch_drop', 'batch_crop','batch_erase','att1','att_module2']
  lr_scheduler: 'multi_step'
  # lr_scheduler: 'warmup'
  stepsize: [20,40]
  print_freq: 200  #20

test:
  batch_size: 128 # 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 4 # -1
  rerank: False
  start_eval: 0
  visactmap: False
  visrank: False       # True
  visrank_topk: 10
